import "./globals.css";
import { Inter, Roboto, Lora, Open_Sans, Poppins } from 'next/font/google';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const roboto = Roboto({ subsets: ['latin'], variable: '--font-roboto' });
const lora = Lora({ subsets: ['latin'], variable: '--font-lora' });
const openSans = Open_Sans({ subsets: ['latin'], variable: '--font-open-sans' });
const poppins = Poppins({ subsets: ['latin'], variable: '--font-poppins', weight: '400' });
export const metadata = {
  title: "Demo",
  description: "Generated by create-next-app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${inter.variable} ${roboto.variable} ${lora.variable} ${openSans.variable} ${poppins.variable}`}>
      <body>{children}</body>
    </html>
  );
} 
